name: ci-cl

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
      
      - name: initialize npm
        run: npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"


      - name: install packages
        run: yarn install

  notify:
    name: notify
    runs-on: ubuntu-latest
    needs: 
      - test
    if: ${{ always() }} 

    steps:
      - name: notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: https://discord.com/api/webhooks/963192166421766194/wEaOk5feH1Dd6U9uol8tzV_Cn8NDNRWRDwUjth3wOsVY__Hib8VkcXmR3sjG8ZWQG4Dr
          username: 'xotomicro'
          title: '${{ github.workflow }}: {{STATUS}}'
          description: '${{ github.event_name }} trigged this {{STATUS}}!'
          include-details: 'true'
          color-success: '#4287f5'
          color-failure: 'eb4034'
          color-cancelled: '0x42daf5'